version: "3.9"
services:

  mysql:
    image: mysql:8.0.23
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
    volumes:
      - ./mysql-data:/var/lib/mysql

  app:
    restart: always
    image: tentativafc/troubleshooting-performance:1.0.0-snapshot
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
    ports:
      - 8080:8080
      - 1099:1099
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 512M
        reservations:
          cpus: 1
          memory: 512M
    depends_on:
      - mysql

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  mysql-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: docker-volume/mysql
  prometheus-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: docker-volume/prometheus
  grafana-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: docker-volume/grafana

